# Generated by Django 5.1 on 2024-08-15 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
